name: Daily Snyk Sync
on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight

jobs:
  sync-to-snyk:
    uses: salemove/glia-security-workflows/.github/workflows/snyk-projects-sync.yaml@master
    secrets:
      SNYK_SYNC_TOKEN: ${{ secrets.SNYK_SYNC_TOKEN }}
      GITHUB_PAT: ${{ secrets.SNYK_GITHUB_SYNC_TOKEN }}
